/**
 * Süper yöneticiye gösterilen kurgu ticaret odası demosu.
 *
 * Bu veri hiçbir müşteri, kullanıcı veya değerlendirme kaydından okunmaz. Demo
 * ekranı gerçek sisteme veri yazmadan ürünün 2.000 yanıtlık bir kampanyada
 * nasıl görüneceğini anlatabilsin diye sayılar burada sabit tutulur.
 */
export const demoChamberDashboard = {
  organization: {
    name: "Marmara Ticaret Odası",
    type: "Ticaret odası",
    memberCount: 2480,
  },
  campaign: {
    name: "2026 Üye Sürdürülebilirlik Olgunluk Araştırması",
    status: "Aktif",
    privacyMode: "Anonim sonuçlar",
    launchedAt: "03 Ağustos 2026",
    deadline: "31 Ağustos 2026",
    lastUpdatedAt: "22 Ağustos 2026, 14:30",
    questionCount: 72,
  },
  participation: {
    invited: 2480,
    submitted: 2000,
    inProgress: 260,
    notStarted: 220,
    completionRate: 80.6,
  },
  results: {
    overallScore: 63.8,
    medianScore: 65,
    leadingMaturity: "Gelişen",
    benchmarkDifference: 4.6,
  },
  esgPillars: [
    {
      key: "E",
      name: "Çevresel",
      score: 62.4,
      benchmark: 59.7,
      weight: 50,
      maturity: "Gelişen",
      change: 4.9,
      color: "var(--series-2)",
      topics: ["İklim ve enerji · 71", "Döngüsellik · 62", "Su yönetimi · 56"],
      finding: "Enerji yönetimi güçlü; su hedefleri ve emisyon envanteri gelişim alanı.",
    },
    {
      key: "S",
      name: "Sosyal",
      score: 68.8,
      benchmark: 64.2,
      weight: 25,
      maturity: "Olgun",
      change: 5.6,
      color: "var(--series-3)",
      topics: ["Çalışan gelişimi · 72", "İSG ve refah · 69", "Toplumsal etki · 65"],
      finding: "Çalışan gelişimi oda genelinin en güçlü pratiği; mikro işletmelerde politika açığı sürüyor.",
    },
    {
      key: "G",
      name: "Yönetişim",
      score: 61.6,
      benchmark: 59.8,
      weight: 25,
      maturity: "Gelişen",
      change: 3.9,
      color: "var(--series-1)",
      topics: ["ESG raporlama · 64", "Risk ve etik · 62", "Tedarik yönetişimi · 59"],
      finding: "Raporlama tabanı oluşmuş; tedarikçi kriterleri ve yönetim kurulu gözetimi güçlendirilmeli.",
    },
  ],
  ironman: {
    current: { velocity: 3.4, endurance: 3.1 },
    benchmark: { velocity: 2.9, endurance: 2.8 },
    target: { velocity: 4.1, endurance: 3.9 },
    threshold: 3,
    quadrant: "IRONMAN",
    quadrantLabel: "Demir Adam",
    description: "Oda ortalaması hızlı aksiyon alma ile kurumsal sürekliliği birlikte taşıyor. Dayanıklılık eşik üzerinde olsa da hızın gerisinde kaldığı için politika ve veri altyapısı önceliklendirilmeli.",
    questionMix: { velocity: 38, endurance: 34 },
    distribution: [
      { key: "IRONMAN", label: "Demir Adam", count: 694, percentage: 34.7, color: "var(--series-2)" },
      { key: "SPRINTER", label: "Sprinter", count: 482, percentage: 24.1, color: "var(--series-3)" },
      { key: "MARATHON_RUNNER", label: "Maraton Koşucusu", count: 436, percentage: 21.8, color: "var(--series-1)" },
      { key: "WALKER", label: "Yaya", count: 388, percentage: 19.4, color: "var(--series-5)" },
    ],
  },
  recommendationSummary: {
    total: 18,
    highPriority: 6,
    memberReach: 1420,
    potentialScoreGain: 11.6,
    byStrategy: { quickWins: 7, projects: 8, bigBets: 3 },
    byStatus: { ready: 6, inProgress: 5, planned: 7 },
  },
  recommendations: [
    {
      id: "demo-rec-1",
      title: "KOBİ Karbon Envanteri Başlangıç Programı",
      esg: "E",
      strategicType: "QUICK_WIN",
      strategicLabel: "Hızlı kazanım",
      priority: "Çok yüksek",
      impact: 9.2,
      memberReach: 680,
      timeframe: "0–6 ay",
      cost: "Düşük",
      status: "Hazır",
      description: "Şablon, eğitim ve ortak danışmanlık havuzuyla üyelerin temel sera gazı envanterini çıkarması.",
    },
    {
      id: "demo-rec-2",
      title: "Su Verimliliği Teknik Destek Paketi",
      esg: "E",
      strategicType: "PROJECT",
      strategicLabel: "Proje",
      priority: "Çok yüksek",
      impact: 8.7,
      memberReach: 580,
      timeframe: "6–12 ay",
      cost: "Orta",
      status: "Planlandı",
      description: "Su yoğun üyelerde ölçüm, kaçak analizi ve azaltım hedefi oluşturma desteği.",
    },
    {
      id: "demo-rec-3",
      title: "Sürdürülebilir Tedarikçi Kriterleri Rehberi",
      esg: "E · G",
      strategicType: "QUICK_WIN",
      strategicLabel: "Hızlı kazanım",
      priority: "Yüksek",
      impact: 8.1,
      memberReach: 1080,
      timeframe: "0–6 ay",
      cost: "Düşük",
      status: "Devam ediyor",
      description: "Satın alma süreçlerine çevresel, sosyal ve etik tedarikçi ölçütlerinin eklenmesi.",
    },
    {
      id: "demo-rec-4",
      title: "ESG Raporlama ve Veri Akademisi",
      esg: "G",
      strategicType: "PROJECT",
      strategicLabel: "Proje",
      priority: "Yüksek",
      impact: 7.8,
      memberReach: 840,
      timeframe: "6–12 ay",
      cost: "Orta",
      status: "Devam ediyor",
      description: "Üyelere veri sahipliği, gösterge seti ve yıllık sürdürülebilirlik raporu hazırlama yetkinliği kazandırılması.",
    },
    {
      id: "demo-rec-5",
      title: "Çalışan Katılımı ve Eşitlik Atölyesi",
      esg: "S",
      strategicType: "QUICK_WIN",
      strategicLabel: "Hızlı kazanım",
      priority: "Orta",
      impact: 7.1,
      memberReach: 620,
      timeframe: "0–6 ay",
      cost: "Düşük",
      status: "Hazır",
      description: "Mikro ve küçük işletmeler için çalışan geri bildirimi, eşitlik ve kapsayıcılık araç seti.",
    },
    {
      id: "demo-rec-6",
      title: "Yeşil Dönüşüm Finansman Masası",
      esg: "E · G",
      strategicType: "BIG_BET",
      strategicLabel: "Büyük yatırım",
      priority: "Çok yüksek",
      impact: 9,
      memberReach: 1250,
      timeframe: "12–24 ay",
      cost: "Yüksek",
      status: "Planlandı",
      description: "Enerji, kaynak verimliliği ve raporlama yatırımlarını uygun finansmanla eşleştiren oda programı.",
    },
  ],
  responseTrend: [
    { label: "03 Ağu", cumulative: 118 },
    { label: "06 Ağu", cumulative: 354 },
    { label: "09 Ağu", cumulative: 620 },
    { label: "12 Ağu", cumulative: 940 },
    { label: "15 Ağu", cumulative: 1225 },
    { label: "17 Ağu", cumulative: 1470 },
    { label: "19 Ağu", cumulative: 1650 },
    { label: "20 Ağu", cumulative: 1805 },
    { label: "21 Ağu", cumulative: 1902 },
    { label: "22 Ağu", cumulative: 2000 },
  ],
  categories: [
    { name: "İklim ve enerji", score: 71, benchmark: 66, change: 7.2 },
    { name: "Çalışanlar ve sosyal etki", score: 69, benchmark: 64, change: 5.6 },
    { name: "Yönetişim ve raporlama", score: 64, benchmark: 61, change: 4.1 },
    { name: "Döngüsellik ve kaynaklar", score: 62, benchmark: 60, change: 3.8 },
    { name: "Sürdürülebilir tedarik", score: 59, benchmark: 58, change: 2.7 },
    { name: "Su yönetimi", score: 56, benchmark: 57, change: 1.9 },
  ],
  maturityDistribution: [
    { label: "Başlangıç", count: 162, percentage: 8.1, color: "var(--series-5)" },
    { label: "Farkındalık", count: 410, percentage: 20.5, color: "var(--series-3)" },
    { label: "Gelişen", count: 704, percentage: 35.2, color: "var(--series-1)" },
    { label: "Olgun", count: 548, percentage: 27.4, color: "var(--series-2)" },
    { label: "Lider", count: 176, percentage: 8.8, color: "var(--series-4)" },
  ],
  sectors: [
    { name: "İmalat", responses: 476, score: 65.8, participation: 84 },
    { name: "Toptan ve perakende", responses: 404, score: 60.4, participation: 78 },
    { name: "Hizmetler", responses: 346, score: 64.9, participation: 82 },
    { name: "İnşaat", responses: 258, score: 58.7, participation: 75 },
    { name: "Gıda", responses: 232, score: 66.2, participation: 86 },
    { name: "Lojistik", responses: 174, score: 61.1, participation: 79 },
    { name: "Bilgi teknolojileri", responses: 110, score: 73.6, participation: 91 },
  ],
  companySizes: [
    { label: "Mikro (1–9)", count: 620, score: 56.8 },
    { label: "Küçük (10–49)", count: 600, score: 61.7 },
    { label: "Orta (50–249)", count: 510, score: 68.5 },
    { label: "Büyük (250+)", count: 270, score: 75.2 },
  ],
  insights: [
    {
      title: "Enerji çalışmaları öne çıkıyor",
      description: "İklim ve enerji 71 puanla en güçlü alan. Üyelerin %62'si tüketimini düzenli izlediğini belirtiyor.",
      tone: "success",
    },
    {
      title: "Emisyon envanteri yaygın değil",
      description: "Yalnızca 680 üye (%34) kurumsal sera gazı envanteri hazırlamış durumda.",
      tone: "warning",
    },
    {
      title: "Tedarik zincirinde gelişim alanı var",
      description: "920 üye (%46) tedarikçi seçiminde sürdürülebilirlik ölçütü kullandığını bildiriyor.",
      tone: "accent",
    },
    {
      title: "Su yönetimi önceliklendirilmeli",
      description: "580 üyenin (%29) belgelenmiş su azaltım hedefi bulunuyor; en düşük kategori puanı 56.",
      tone: "danger",
    },
  ],
} as const;

export type DemoChamberDashboard = typeof demoChamberDashboard;
